### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by silver46** [YutoHiruta/SubGraphMergine-Python#1]
Dear Yuto,
this algorithm is used in some scientific paper?
Best regards,
Nico.

**Comment by YutoHiruta** [comment]
Dear Nico.

Thank you for your question.
This implement based on The algorithm "SubGraph Marging". 
The paper about original "SubGraph Merging" is follows.

TAPDIYA, Ashish; FULP, Errin W. Towards optimal firewall rule ordering utilizing directed acyclical graphs. In: 2009 Proceedings of 18th International Conference on Computer Communications and Networks. IEEE, 2009. p. 1-6.

But, this algorithm is improved a part. The improvements were made by my senior, so I don't know exactly where were improved.

I'm sorry not to speak english fluently.
If this answer your question, I glad.

**Comment by silver46** [comment]
Hey Yuto,
do you know if is possible to have the code of this paper "T. Fuchino, T. Harada, K. Tanaka and K. Mikawa, "Acceleration of Packet Classification Using Adjacency List of Rules," 2019 28th International Conference on Computer Communication and Networks (ICCCN), 2019, pp. 1-9, doi: 10.1109/ICCCN.2019.8846923." ?
Because i want to compare the efficiency of my algorithm.
Thanks for your time.
Best regards,
Nico.

**Comment by YutoHiruta** [comment]
Dear Nico.

I'm sorry. I'm not author written that paper, so I can't provide the program on my judgement.
Follow is The Github account of the author written that paper. Please ask this person directly.

https://github.com/Takashi-Fuchino

**Comment by silver46** [comment]
Hey Yuto,
thanks for the help, have a great day!
Bye,
Nico.
